### ISSUE TITLE
magit section highlight face

### ISSUE THREAD

**Issue by vidjuheffex** [caffo/monotropic-theme#5]
The size changing as I key down through entries is distracting IMO.

   `(magit-section-highlight ((t (:inherit default))))

I dropped the 'default' from mine.  

and went with:
 '(magit-section-highlight ((t (:inherit nil :weight bold))))

so the entries bold, and the heading stays the same without popping in size as its high-lit

**Comment by caffo** [comment]
I think It makes sense. Will update it.

**Comment by caffo** [comment]
Done!
